### PR TITLE
created a panda animation using html & css

### PR DESCRIPTION
**Pull request by Robinrai2612**
@Durgesh4993 I have submitted a pull request. Please consider merging it and apply the 'hacktoberfest2023' label. I would  like to connect with you.

### CODE REVIEW

**Comment by Robinrai2612** [comment]
@Durgesh4993 Kindly merge my PR.

**Comment by Durgesh4993** [comment]
connect with me -
Github : https://github.com/Durgesh4993
LinkedIn : https://www.linkedin.com/in/durgesh4993/

**Comment by Robinrai2612** [comment]
@Durgesh4993 I have already raised the Pull request. Please merge it.

**Comment by Robinrai2612** [comment]
@Durgesh4993 Pls add label hacktoberfest-accepted label and merge my PR as in my profile its showing NOT-ACCEPTED .

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Pull request merged**
